### ISSUE TITLE
maybe the pretrained weight is different from cfg

### ISSUE THREAD

**Issue by Johnson-yue** [Hephyrius/Stylegan2-Ada-Google-Colab-Starter-Notebook#2]
> ValueError: Cannot feed value of shape (3, 3, 512, 256) for Tensor 'G_synthesis_3/64x64/Conv0_up/weight/new_value:0', which has shape '(3, 3, 512, 512)'

 when I was using  ffhq-res256-mirror-paper256-noaug.pkl pretrained weight ,  it can not be loaded 
then I print the layers_information:

**pretrained weight : rGs** = 

> rG = 
> 
> G_main                        Params    OutputShape         WeightShape     
> ---                           ---       ---                 ---             
> latents_in                    -         (?, 512)            -               
> labels_in                     -         (?, 0)              -               
> G_mapping/Normalize           -         (?, 512)            -               
> G_mapping/Dense0              262656    (?, 512)            (512, 512)      
> G_mapping/Dense1              262656    (?, 512)            (512, 512)      
> G_mapping/Dense2              262656    (?, 512)            (512, 512)      
> G_mapping/Dense3              262656    (?, 512)            (512, 512)      
> G_mapping/Dense4              262656    (?, 512)            (512, 512)      
> G_mapping/Dense5              262656    (?, 512)            (512, 512)      
> G_mapping/Dense6              262656    (?, 512)            (512, 512)      
> G_mapping/Dense7              262656    (?, 512)            (512, 512)      
> G_mapping/Broadcast           -         (?, 14, 512)        -               
> dlatent_avg                   -         (512,)              -               
> Truncation/Lerp               -         (?, 14, 512)        -               
> G_synthesis/4x4/Const         8192      (?, 512, 4, 4)      (1, 512, 4, 4)  
> G_synthesis/4x4/Conv          2622465   (?, 512, 4, 4)      (3, 3, 512, 512)
> G_synthesis/4x4/ToRGB         264195    (?, 3, 4, 4)        (1, 1, 512, 3)  
> G_synthesis/8x8/Conv0_up      2622465   (?, 512, 8, 8)      (3, 3, 512, 512)
> G_synthesis/8x8/Conv1         2622465   (?, 512, 8, 8)      (3, 3, 512, 512)
> G_synthesis/8x8/Upsample      -         (?, 3, 8, 8)        -               
> G_synthesis/8x8/ToRGB         264195    (?, 3, 8, 8)        (1, 1, 512, 3)  
> G_synthesis/16x16/Conv0_up    2622465   (?, 512, 16, 16)    (3, 3, 512, 512)
> G_synthesis/16x16/Conv1       2622465   (?, 512, 16, 16)    (3, 3, 512, 512)
> G_synthesis/16x16/Upsample    -         (?, 3, 16, 16)      -               
> G_synthesis/16x16/ToRGB       264195    (?, 3, 16, 16)      (1, 1, 512, 3)  
> G_synthesis/32x32/Conv0_up    2622465   (?, 512, 32, 32)    (3, 3, 512, 512)
> G_synthesis/32x32/Conv1       2622465   (?, 512, 32, 32)    (3, 3, 512, 512)
> G_synthesis/32x32/Upsample    -         (?, 3, 32, 32)      -               
> G_synthesis/32x32/ToRGB       264195    (?, 3, 32, 32)      (1, 1, 512, 3)  
> G_synthesis/64x64/**Conv0_up    1442561   (?, 256, 64, 64)    (3, 3, 512, 256)**
> G_synthesis/64x64/Conv1       721409    (?, 256, 64, 64)    (3, 3, 256, 256)
> G_synthesis/64x64/Upsample    -         (?, 3, 64, 64)      -               
> G_synthesis/64x64/ToRGB       132099    (?, 3, 64, 64)      (1, 1, 256, 3)  
> G_synthesis/128x128/Conv0_up  426369    (?, 128, 128, 128)  (3, 3, 256, 128)
> G_synthesis/128x128/Conv1     213249    (?, 128, 128, 128)  (3, 3, 128, 128)
> G_synthesis/128x128/Upsample  -         (?, 3, 128, 128)    -               
> G_synthesis/128x128/ToRGB     66051     (?, 3, 128, 128)    (1, 1, 128, 3)  
> G_synthesis/256x256/Conv0_up  139457    (?, 64, 256, 256)   (3, 3, 128, 64) 
> G_synthesis/256x256/Conv1     69761     (?, 64, 256, 256)   (3, 3, 64, 64)  
> G_synthesis/256x256/Upsample  -         (?, 3, 256, 256)    -               
> G_synthesis/256x256/ToRGB     33027     (?, 3, 256, 256)    (1, 1, 64, 3)   
> ---                           ---       ---                 ---             
> Total                         24767458

**build G network :**  

> G = 
> 
> G                             Params    OutputShape         WeightShape     
> ---                           ---       ---                 ---             
> latents_in                    -         (?, 512)            -               
> labels_in                     -         (?, 0)              -               
> G_mapping/Normalize           -         (?, 512)            -               
> G_mapping/Dense0              262656    (?, 512)            (512, 512)      
> G_mapping/Dense1              262656    (?, 512)            (512, 512)      
> G_mapping/Dense2              262656    (?, 512)            (512, 512)      
> G_mapping/Dense3              262656    (?, 512)            (512, 512)      
> G_mapping/Dense4              262656    (?, 512)            (512, 512)      
> G_mapping/Dense5              262656    (?, 512)            (512, 512)      
> G_mapping/Dense6              262656    (?, 512)            (512, 512)      
> G_mapping/Dense7              262656    (?, 512)            (512, 512)      
> G_mapping/Broadcast           -         (?, 14, 512)        -               
> dlatent_avg                   -         (512,)              -               
> Truncation/Lerp               -         (?, 14, 512)        -               
> G_synthesis/4x4/Const         8192      (?, 512, 4, 4)      (1, 512, 4, 4)  
> G_synthesis/4x4/Conv          2622465   (?, 512, 4, 4)      (3, 3, 512, 512)
> G_synthesis/4x4/ToRGB         264195    (?, 3, 4, 4)        (1, 1, 512, 3)  
> G_synthesis/8x8/Conv0_up      2622465   (?, 512, 8, 8)      (3, 3, 512, 512)
> G_synthesis/8x8/Conv1         2622465   (?, 512, 8, 8)      (3, 3, 512, 512)
> G_synthesis/8x8/Upsample      -         (?, 3, 8, 8)        -               
> G_synthesis/8x8/ToRGB         264195    (?, 3, 8, 8)        (1, 1, 512, 3)  
> G_synthesis/16x16/Conv0_up    2622465   (?, 512, 16, 16)    (3, 3, 512, 512)
> G_synthesis/16x16/Conv1       2622465   (?, 512, 16, 16)    (3, 3, 512, 512)
> G_synthesis/16x16/Upsample    -         (?, 3, 16, 16)      -               
> G_synthesis/16x16/ToRGB       264195    (?, 3, 16, 16)      (1, 1, 512, 3)  
> G_synthesis/32x32/Conv0_up    2622465   (?, 512, 32, 32)    (3, 3, 512, 512)
> G_synthesis/32x32/Conv1       2622465   (?, 512, 32, 32)    (3, 3, 512, 512)
> G_synthesis/32x32/Upsample    -         (?, 3, 32, 32)      -               
> G_synthesis/32x32/ToRGB       264195    (?, 3, 32, 32)      (1, 1, 512, 3)  
> G_synthesis/64x64/**Conv0_up    2622465   (?, 512, 64, 64)    (3, 3, 512, 512)**
> G_synthesis/64x64/Conv1       2622465   (?, 512, 64, 64)    (3, 3, 512, 512)
> G_synthesis/64x64/Upsample    -         (?, 3, 64, 64)      -               
> G_synthesis/64x64/ToRGB       264195    (?, 3, 64, 64)      (1, 1, 512, 3)  
> G_synthesis/128x128/Conv0_up  1442561   (?, 256, 128, 128)  (3, 3, 512, 256)
> G_synthesis/128x128/Conv1     721409    (?, 256, 128, 128)  (3, 3, 256, 256)
> G_synthesis/128x128/Upsample  -         (?, 3, 128, 128)    -               
> G_synthesis/128x128/ToRGB     132099    (?, 3, 128, 128)    (1, 1, 256, 3)  
> G_synthesis/256x256/Conv0_up  426369    (?, 128, 256, 256)  (3, 3, 256, 128)
> G_synthesis/256x256/Conv1     213249    (?, 128, 256, 256)  (3, 3, 128, 128)
> G_synthesis/256x256/Upsample  -         (?, 3, 256, 256)    -               
> G_synthesis/256x256/ToRGB     66051     (?, 3, 256, 256)    (1, 1, 128, 3)  
> ---                           ---       ---                 ---             
> Total                         30034338                                  

The two networks are not the same！！

**Comment by Hephyrius** [comment]
Sorry about that - I ended up importing the wrong pickle for transfer learning - Fixed in latest version!
